- name: Dimensions on stand
  spec: 70.1 x 90.8 x 41.5 cm | 27.6 x 35.8 x 16.3 in
- name: Dimensions on wall
  spec: 70.1 x 21.3 cm | 27.6 x 8.4 in
- name: Weight
  spec: 15 kg (incl. legs) | 14.2 kg (without legs) | 33.1 lbs (incl. legs) | 31.5 lbs (without legs)
- name: Power consumption 
  spec: Typical 23 watts | Standby 0.4 watts
- name: Effective frequency range
  spec: 33.1 - 25.000 Hz
- name: Driver units
  spec: 1 x 8' woofer | 2 x 3” midrange | 2 x 3⁄4” tweeters
- name: Cabinet principle
  spec: Bass-reflex
- name: Room adaptation 
  spec: Manual position switch, wall, corner and free standing
- name: Connectivity
  spec: 1 x USB iPod/iPhone/iPad connector | 1 x Line-in | 1 x Ethernet
- name: Wireless connectivity
  spec: WLAN - 802.11b/g/n (2.4GHz & 5GHz) | Apple AirPlay | DLNA wireless streaming | Bluetooth 4.0 | Google Cast
- name: Supported streaming services
  spec: Spotify | TuneIn | Deezer
- name: On Device controls
  spec: Swipe hand across the top to turn volume up or down. Rest hand on the top sensor for a few seconds to mute sound. Tap to the right to play next track and left to play previous track. Short tap in the centre to initiate last played source.
- name: Designed by 
  spec: Øivind Alexander Slaatto
- name: Base color
  spec: DS C7 White comes standardly with maple legs | DS C7 Black comes standardly with walnut legs
- name: Included cover 
  spec: White or black
- name: Additional cover colors
  spec: Silver, red, green, brown, blue and black | Covers by Kvadrat | Light grey, Dark grey, Dark rose and Dusty blue
- name: Legs and wall bracket 
  spec: Legs in oak, maple or walnut and wall bracket can be bought as an accessory.